
services:
  img-scan-postgres:
    image: postgres:16
    container_name: img-scan-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - img_scan_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
      - extern

volumes:
  img_scan_postgres_data:

networks:
  backend:
  extern:
    driver: bridge
  
